services:
#start postgresdb service from docker repo
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  #start mongodb service from docker repo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  
  #start rabbitmq service from docker repo
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  #Building AuctionService from my local file location
  auction-svc:
    image: ceeobi/auction-svc:latest #We assign the image a name here
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq #Assigns the 'rabbitmq' container, above in docker to 'Host in RabbitMq in Configfile'
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=passw0rd;Database=auctions
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq      

volumes:
  pgdata:
  mongodata:
      