services:
#start postgresdb service from docker repo
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  #start mongodb service from docker repo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  
  #start rabbitmq service from docker repo
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  #Building AuctionService from my local file location
  auction-svc:
    image: ceeobi/auction-svc:latest #We assign the image a name here
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:7777
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq #Assigns the 'rabbitmq' container, above in docker to 'Host in RabbitMq in Configfile'
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=passw0rd;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on: #Services above
      - postgres
      - rabbitmq     

  #Building SearchService from my local file location
  search-svc:
    image: ceeobi/search-svc:latest 
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbDefaultConnection=mongodb://root:passw0rd@mongo
      - IdentityServiceUrl=http://identity-svc
      - AuctionServiceUrl:http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongo
      - rabbitmq 
      #- auction-svc => No need because resilence is already setup
  
  #Building IdentityService from my local file location
  identity-svc:
    image: ceeobi/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=passw0rd;Database=identity
    ports:
      - 5000:80
      #
    deploy:
      resources:
        limits:
          memory: 8GB
        reservations:
          memory: 2GB
      #
    depends_on:
      - postgres

  #Building GatewayService from my local file location
  gateway-svc:
    image: ceeobi/gateway-svc:latest 
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

  #Building BiddingService from my local file location
  bid-svc:
    image: ceeobi/bid-svc:latest 
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:passw0rd@mongo
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction:http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongo
      - rabbitmq 
  
  #Building NotifyService from my local file location
  notify-svc:
    image: ceeobi/notify-svc:latest 
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq 
     
#Volumes
volumes:
  pgdata:
  mongodata:
      