import type { Metadata } from 'next'
import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from '@/provider/ToasterProvider'


export const metadata: Metadata = {
  title: 'Carsbidi',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode})
{
  return (
    <html lang="en">
      <ToasterProvider/>      
      <body className="">
        <Navbar />
        <main className='container mx-auto px-5 pt-10'>{children}</main>        
      </body>
    </html>
  )
}
