import type { Metadata } from 'next'
import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from '@/provider/ToasterProvider'
import SignalRProvider from '@/provider/SignalRProvider'


export const metadata: Metadata = {
  title: 'Carsbidi',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode})
{
  return (
    <html lang="en">
         
      <body className="">
      <ToasterProvider/>   
        <Navbar />
        <main className='container mx-auto px-5 pt-10'>
          <SignalRProvider>
              {children}
          </SignalRProvider>
        </main>        
      </body>
      
    </html>
  )
}
